Bikes/Controllers/BikeController.cs
using Bikes.AppDbContext;
using Bikes.Helpers;
using Bikes.Models;
using Bikes.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using cloudscribe.Pagination.Models;
namespace Bikes.Controllers
{
    public class BikeController : Controller
    {
        private readonly VroomDbContext vroomDbContext;
        private readonly IWebHostEnvironment _hostingEnvironment;


        [BindProperty]
        public BikeViewModel BikeVM { get; set; }
        public BikeController(VroomDbContext vroomDbContext, IWebHostEnvironment hostingEnvironment)
        {
            this.vroomDbContext = vroomDbContext;
            BikeVM = new BikeViewModel()
            {
                Makes = vroomDbContext.Makes.ToList(),
                Models = vroomDbContext.Models.ToList(),
                Bike = new Models.Bike(),
            };
            _hostingEnvironment = hostingEnvironment;

        }


        public IActionResult Index(String searchString, String sortOrder,int pageNumber=1, int pageSize=2)
        {
            ViewBag.CurrentSortOrder = sortOrder;
            ViewBag.CurrentFilter = searchString;
            ViewBag.PriceSortParam = String.IsNullOrEmpty(sortOrder) ? "Price_desc" : "";
            int ExcludeRecords = (pageSize * pageNumber) - pageSize;
            var bikes = from b in vroomDbContext.Bikes.Include(m => m.Make).Include(m => m.Model)
                        select b;
            var BikeCount = bikes.Count();
            if (!String.IsNullOrEmpty(searchString) )
            {
                bikes = bikes.Where(b => b.Make.Name.Contains(searchString));
                BikeCount = bikes.Count();
            }
            //Sorting Logic
            switch (sortOrder)
            {
                case "Price_desc":
                    bikes = bikes.OrderByDescending(b => b.Price);
                    break;
                default:
                    bikes = bikes.OrderBy(b => b.Price);
                    break;
            }
            bikes = bikes
                .Skip(ExcludeRecords)
                .Take(pageSize);
            var result = new PagedResult<Bike>
            {
                Data = bikes.AsNoTracking().ToList(),
                TotalItems = BikeCount,
                PageNumber = pageNumber,
                PageSize = pageSize
            };
            return View(result);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            BikeVM.Bike= vroomDbContext.Bikes.SingleOrDefault(b=> b.Id == id);
            BikeVM.Models= vroomDbContext.Models.Where(m=>m.Make== BikeVM.Bike.Make);
            if (BikeVM.Bike == null )
            {
                return NotFound();
            }
            return View(BikeVM);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(BikeVM);
        }

        [HttpPost, ActionName("Create")]
        public IActionResult CreatePost()
        {
            //if (ModelState.IsValid)
            //{
            vroomDbContext.Add(this.BikeVM.Bike);
            vroomDbContext.SaveChanges();
            var BikeId = BikeVM.Bike.Id;
            string wwrootPath = _hostingEnvironment.WebRootPath;
            var files = HttpContext.Request.Form.Files;
            var savedBike = vroomDbContext.Bikes.Find(BikeId);
            if (files.Count != 0)
            {
                var ImagePath = @"images\bike\";
                var extension = Path.GetExtension(files[0].FileName);
                var relativeImagePath = ImagePath + BikeId + extension;
                var absImagePath = Path.Combine(wwrootPath, relativeImagePath);

                using (var FileStream = new FileStream(absImagePath, FileMode.Create))
                {
                    files[0].CopyTo(FileStream);
                }
                savedBike.ImagePath = relativeImagePath;
                vroomDbContext.SaveChanges();
            }

            return RedirectToAction(nameof(Index));
            //}
            //return View(modelVm);
        }


        public IActionResult Delete(int id)
        {
            {
                var bike = vroomDbContext.Bikes.Find(id);
                if (bike == null)
                {
                    return NotFound();
                }
                vroomDbContext.Bikes.Remove(bike);
                vroomDbContext.SaveChanges();
                return (RedirectToAction(nameof(Index)));
            }
        }


        //[HttpGet]
        //public IActionResult Edit(int id)
        //{
        //    BikeVM.Bike = vroomDbContext.Bikes.Include(m => m.Make).Include(m => m.Model).SingleOrDefault(m => m.Id == id);
        //    if (BikeVM.Bike == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(BikeVM);
        //}


        //[HttpPost, ActionName("Edit")]
        //public IActionResult EditPost()
        //{
        //    vroomDbContext.Update(this.BikeVM.Bike);
        //    vroomDbContext.SaveChanges();
        //    return (RedirectToAction(nameof(Index)));
        //
        //}
    }
}

Bikes/Controllers/MakeController.cs
using Bikes.AppDbContext;
using Bikes.Helpers;
using Bikes.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bikes.Controllers
{
    [Authorize(Roles = Roles.Admin + "," + Roles.Executive)]
    public class MakeController : Controller
    {
        private readonly VroomDbContext vroomDbContext;

        public MakeController(VroomDbContext vroomDbContext)
        {
            this.vroomDbContext = vroomDbContext;
        }

        public IActionResult Index()
        {
            return View(vroomDbContext.Makes.ToList());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Make make)
        {
            if (ModelState.IsValid)
            {
                vroomDbContext.Add(make);
                vroomDbContext.SaveChanges();
                return (RedirectToAction(nameof(Index)));
            }
            return View(make);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var make = vroomDbContext.Makes.Find(id);
            if (make == null)
            {
                return NotFound();
            }
            vroomDbContext.Makes.Remove(make);
            vroomDbContext.SaveChanges();
            return (RedirectToAction(nameof(Index)));
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var make = vroomDbContext.Makes.Find(id);
            if (make == null)
            {
                return NotFound();
            }
            return View(make);
        }


        [HttpPost]
        public IActionResult Edit(Make make)
        {
            if (ModelState.IsValid)
            {
                vroomDbContext.Update(make);
                vroomDbContext.SaveChanges();
                return (RedirectToAction(nameof(Index)));
            }
            return View(make);
        }
    }

}

Bikes/Controllers/ModelController.cs
using Bikes.AppDbContext;
using Bikes.Helpers;
using Bikes.Models;
using Bikes.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Bikes.Controllers
{
    [Authorize(Roles = Roles.Admin + "," + Roles.Executive)]
    public class ModelController : Controller
    {
        private readonly VroomDbContext vroomDbContext;

        [BindProperty]
        public ModelViewModel modelVm { get; set; }
        public ModelController(VroomDbContext vroomDbContext)
        {
            this.vroomDbContext = vroomDbContext;
            modelVm = new ModelViewModel()
            {
                Makes = vroomDbContext.Makes.ToList(),
                Model = new Models.Model()
            };

        }

        public IActionResult Index()
        {

            var model = vroomDbContext.Models.Include(m => m.Make);
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(modelVm);
        }

        [HttpPost, ActionName("Create")]
        public IActionResult CreatePost()
        {
            //if (ModelState.IsValid)
            //{
            vroomDbContext.Add(this.modelVm.Model);
            vroomDbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
            //}
            //return View(modelVm);
        }


        public IActionResult Delete(int id)
        {
            {
                var model = vroomDbContext.Models.Find(id);
                if (model == null)
                {
                    return NotFound();
                }
                vroomDbContext.Models.Remove(model);
                vroomDbContext.SaveChanges();
                return (RedirectToAction(nameof(Index)));
            }
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            modelVm.Model = vroomDbContext.Models.Include(m => m.Make).SingleOrDefault(m => m.Id == id);
            if (modelVm.Model == null)
            {
                return NotFound();
            }
            return View(modelVm);
        }


        [HttpPost, ActionName("Edit")]
        public IActionResult EditPost()
        {
            vroomDbContext.Update(this.modelVm.Model);
            vroomDbContext.SaveChanges();
            return (RedirectToAction(nameof(Index)));

        }
    }
}

Bikes/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Bikes.Helpers
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="../wwwroot/favicon.ico" type="image/x-icon" />
    <link rel="icon" href="../wwwroot/favicon.ico" type="image/x-icon" />
    <title>@ViewData["Title"] - Bikes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/lib/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/lib/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/lib/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/lib/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/lib/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/lib/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
    <!-- Template Main CSS File -->
    <link href="~/css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bikes.styles.css" asp-append-version="true" />
</head>
<body>
    <header id="header" class="fixed-top " style="background-color:#37517e ; height:9.5%">
        <div class="container d-flex align-items-center">

            <a asp-controller="Home" asp-action="Index" class="logo me-auto"><img src="~/lib/images/logo.png" alt="motozoom" class="img-fluid"></a>
            <h1 class="logo me-auto"><a asp-controller="Home" asp-action="Index">MotoZOOM</a></h1>

            <nav id="navbar" class="navbar">
                <ul>
                    <li><a href="@Url.Action("Index", "Home")#">Home</a></li>
                    <li><a class="nav-link scrollto" href="@Url.Action("Index", "Home")#about" >About</a></li>
                    <li><a class="nav-link scrollto" href="@Url.Action("Index", "Home")#services" >Services</a></li>
                    <li><a class="nav-link scrollto" href="@Url.Action("Index", "Home")#portfolio">Gallery</a></li>
                    <li><a class="nav-link scrollto" href="@Url.Action("Index", "Home")#team">Team</a></li>
                    <li><a class="nav-link scrollto" href="@Url.Action("Index", "Home")#contact">Contact</a></li>
                    <li><a class="nav-link scrollto" href="@Url.Action("Index", "Bike")">Bikes</a></li>

                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="dropdown">
                            <a href="#"><span>Masters</span> <i class="bi bi-chevron-down"></i></a>
                            <ul>
                                <li><a asp-controller="Make" asp-action="Index">Makes</a></li>
                                <li><a asp-controller="Model" asp-action="Index">Models</a></li>
                            </ul>
                        </li>
                    }
                    
                </ul>
                <partial name="_LoginPartial" />
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->

        </div>
    </header><!-- End Header -->
    <div style="margin-top:4%">
        @RenderBody()
        <hr />
        <!-- ======= Footer ======= -->
    </div>
    <footer id="footer" style="bottom:0;width:100%">
        <div class="container footer-bottom clearfix">
            <div class="copyright">
                &copy; Copyright <strong><span>MotoZoom</span></strong>. All Rights Reserved
            </div>
            <div class="credits">
                Built by Nour Eddine Ben Nejma & Dali Selmi
            </div>
        </div>
    </footer><!-- End Footer -->

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/b17ae2511b.js" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- Vendor JS Files -->
    <script src="~/lib/vendor/aos/aos.js"></script>
    <script src="~/lib/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/lib/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/lib/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/lib/vendor/waypoints/noframework.waypoints.js"></script>
    <script src="~/lib/vendor/php-email-form/validate.js"></script>
    <!-- Template Main JS File -->
    <script src="~/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Bikes/Views/Shared/_PaginationPartial.cshtml
<cs-pager cs-paging-pagenumber=(int)Model.PageNumber
          cs-paging-totalitems=(int)Model.TotalItems
          cs-paging-pagesize=(int)Model.PageSize
          cs-pagenumber-param="pagenumber"
          asp-route-sortOrder="@ViewBag.CurrentSortOrder"
          asp-route-searchString="@ViewBag.CurrentFilter"
          asp-controller=@ViewData["Controller"]
          asp-action=@ViewData["Action"]
          cs-pager-li-current-class="page-item active"
          cs-pager-li-other-class="page-item"
          cs-pager-li-non-active-class="page-item disabled"
          cs-pager-link-current-class="page-link"
          cs-pager-link-other-class="page-link">
</cs-pager>

Bikes/Views/Shared/_TableButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<td class="text-end">
    <div class="btn-group" role="group">
        <a type="button" class="btn btn-primary rounded-2 me-1" href="@Url.Action("Edit","Model",new {id=Model})" style="background-color : steelblue"><i class="far fa-edit"></i></a>
        <form action="Delete" method="post">
            <button onclick="if(!confirm('Are you sure you want to delete this item?')){return(false)}" type="submit" class="btn btn-danger rounded-2" asp-action="Delete" asp-route-id="@Model"><i class="fa-solid fa-trash"></i> </button>
        </form>
    </div>
</td>

Bikes/Views/Shared/_TableButtonPartialofMakes.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<td class="text-end">
    <div class="btn-group" role="group">
        <a type="button" class="btn btn-primary rounded-2 me-1" href="@Url.Action("Edit","Make",new {id=Model})" style="background-color : steelblue"><i class="far fa-edit"></i></a>
        <form action="Delete" method="post">
            <button onclick="if(!confirm('Are you sure you want to delete this item?')){return(false)}" type="submit" class="btn btn-danger rounded-2" asp-action="Delete" asp-controller="Make" asp-route-id="@Model"><i class="fa-solid fa-trash"></i> </button>
        </form>
    </div>
</td>

Bikes/Views/Shared/_tableButtonPartialofBikes.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<td class="text-end">
    <div class="btn-group" role="group">
        <a type="button" class="btn btn-primary rounded-2 me-1" href="@Url.Action("Edit","Bike",new {id=Model})" style="background-color : steelblue"><i class="far fa-edit"></i></a>
        <form action="Delete" method="post">
            <button onclick="if(!confirm('Are you sure you want to delete this item?')){return(false)}" type="submit" class="btn btn-danger rounded-2" asp-action="Delete" asp-controller="Bike" asp-route-id="@Model"><i class="fa-solid fa-trash"></i> </button>
        </form>
    </div>
</td>